// client/src/components/VideoCard.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { getVideo, updateMetadata, type Video } from '../api';
  import { goto } from 'svelte-spa-router';
  import AutocompleteInput from './AutocompleteInput.svelte';

  export let id: string;

  let video: Video | null = null;
  let loading: boolean = true;
  let error: string | null = null;
  
  // Edit mode state
  let isEditing: boolean = false;
  let editForm: {
    perf_date: string;
    group_name: string;
    artist_name: string;
    song_title: string;
    event: string;
    camera_type: string;
  } = {
    perf_date: '',
    group_name: '',
    artist_name: '',
    song_title: '',
    event: '',
    camera_type: '',
  };
  let saving: boolean = false;
  let saveError: string | null = null;

  async function fetchVideo() {
    loading = true;
    error = null;
    try {
      video = await getVideo(id);
      
      // Initialize edit form with current values
      editForm = {
        perf_date: formatDateForEdit(video.perf_date),
        group_name: video.group_name || '',
        artist_name: video.artist_name || '',
        song_title: video.song_title || '',
        event: video.event ? video.event.replace('@', '') : '',
        camera_type: video.camera_type || '',
      };
    } catch (err) {
      error = err instanceof Error ? err.message : 'Failed to fetch video';
    } finally {
      loading = false;
    }
  }

  function formatDateForEdit(dateString: string | null): string {
    if (!dateString) return '';
    const date = new Date(dateString);
    const year = String(date.getFullYear()).slice(-2);
    const month = String(date.getMonth() + 1).padStart(2, '0');
    const day = String(date.getDate()).padStart(2, '0');
    return `${year}${month}${day}`;
  }

  function toggleEditMode() {
    isEditing = !isEditing;
    saveError = null;
  }

  async function handleSave() {
    saving = true;
    saveError = null;
    try {
      const updateData = {
        perf_date: editForm.perf_date || null,
        group_name: editForm.group_name || null,
        artist_name: editForm.artist_name || null,
        song_title: editForm.song_title || null,
        event: editForm.event ? '@' + editForm.event.toUpperCase() : null,
        camera_type: editForm.camera_type || null,
      };
      
      video = await updateMetadata(id, updateData);
      isEditing = false;
      
      // Refresh the video data
      await fetchVideo();
    } catch (err) {
      saveError = err instanceof Error ? err.message : 'Failed to save changes';
    } finally {
      saving = false;
    }
  }

  function handleCancel() {
    if (video) {
      editForm = {
        perf_date: formatDateForEdit(video.perf_date),
        group_name: video.group_name || '',
        artist_name: video.artist_name || '',
        song_title: video.song_title || '',
        event: video.event ? video.event.replace('@', '') : '',
        camera_type: video.camera_type || '',
      };
    }
    isEditing = false;
    saveError = null;
  }

  function getStatusColor(status: string): string {
    switch (status) {
      case 'new': return 'bg-green-100 text-green-800';
      case 'needs_review': return 'bg-red-100 text-red-800';
      case 'pending': return 'bg-yellow-100 text-yellow-800';
      case 'processing': return 'bg-blue-100 text-blue-800';
      case 'ready': return 'bg-purple-100 text-purple-800';
      case 'completed': return 'bg-gray-100 text-gray-800';
      case 'error': return 'bg-red-200 text-red-900';
      default: return 'bg-gray-100 text-gray-800';
    }
  }

  function formatDateDisplay(dateString: string | null): string {
    if (!dateString) return '-';
    return new Date(dateString).toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
    });
  }

  function goBack() {
    goto('/videos');
  }

  onMount(() => {
    fetchVideo();
  });
</script>

<div class="p-6 max-w-5xl mx-auto">
  <button 
    on:click={goBack}
    class="mb-4 text-pink-600 hover:text-pink-800 font-medium"
  >
    ← Back to Videos
  </button>

  {#if loading}
    <div class="flex justify-center items-center py-12">
      <div class="animate-spin rounded-full h-12 w-12 border-b-2 border-pink-500"></div>
    </div>
  {:else if error}
    <div class="bg-red-50 border border-red-200 text-red-700 px-4 py-3 rounded-md">
      {error}
    </div>
  {:else if video}
    <div class="bg-white rounded-lg shadow-lg overflow-hidden">
      <!-- Header -->
      <div class="bg-gradient-to-r from-pink-500 to-purple-600 px-6 py-4">
        <div class="flex items-center justify-between">
          <h1 class="text-2xl font-bold text-white truncate">{video.original_title}</h1>
          <span class="inline-flex px-3 py-1 text-sm font-semibold rounded-full bg-white/20 text-white">
            {video.status}
          </span>
        </div>
      </div>

      <div class="p-6">
        <div class="grid grid-cols-1 md:grid-cols-3 gap-6">
          <!-- Thumbnail -->
          <div class="md:col-span-1">
            <img 
              src="https://img.youtube.com/vi/{video.youtube_id}/maxresdefault.jpg" 
              alt="Thumbnail"
              class="w-full rounded-lg shadow-md"
              on:error={(e) => {
                const target = e.target as HTMLImageElement;
                target.src = `https://img.youtube.com/vi/${video.youtube_id}/mqdefault.jpg`;
              }}
            />
            <a 
              href="https://www.youtube.com/watch?v={video.youtube_id}" 
              target="_blank" 
              rel="noopener noreferrer"
              class="mt-2 block text-center text-sm text-pink-600 hover:text-pink-800"
            >
              Watch on YouTube
            </a>
          </div>

          <!-- Details -->
          <div class="md:col-span-2 space-y-4">
            <div>
              <h3 class="text-sm font-medium text-gray-500">Published Date</h3>
              <p class="text-gray-900">{formatDateDisplay(video.published_at)}</p>
            </div>

            {#if video.channel_title}
              <div>
                <h3 class="text-sm font-medium text-gray-500">Channel</h3>
                <p class="text-gray-900">{video.channel_title}</p>
              </div>
            {/if}

            {#if video.playlist_title}
              <div>
                <h3 class="text-sm font-medium text-gray-500">Playlist</h3>
                <p class="text-gray-900">{video.playlist_title}</p>
              </div>
            {/if}

            <!-- Metadata Section -->
            <div class="border-t pt-4 mt-4">
              <div class="flex items-center justify-between mb-4">
                <h2 class="text-lg font-semibold text-gray-900">Metadata</h2>
                {#if !isEditing}
                  <button
                    on:click={toggleEditMode}
                    class="px-4 py-2 text-sm font-medium text-pink-600 border border-pink-600 rounded-md hover:bg-pink-50"
                  >
                    Edit
                  </button>
                {/if}
              </div>

              {#if isEditing}
                <div class="space-y-4">
                  <AutocompleteInput
                    label="Performance Date (YYMMDD)"
                    type="groups"
                    placeholder="e.g., 240315"
                    bind:value={editForm.perf_date}
                  />
                  <AutocompleteInput
                    label="Group Name"
                    type="groups"
                    placeholder="Enter group name"
                    bind:value={editForm.group_name}
                  />
                  <AutocompleteInput
                    label="Artist Name"
                    type="artists"
                    placeholder="Enter artist name"
                    bind:value={editForm.artist_name}
                  />
                  <AutocompleteInput
                    label="Song Title"
                    type="songs"
                    placeholder="Enter song title"
                    bind:value={editForm.song_title}
                  />
                  <AutocompleteInput
                    label="Event"
                    type="events"
                    placeholder="Enter event name"
                    bind:value={editForm.event}
                  />
                  <div>
                    <label class="block text-sm font-medium text-gray-700 mb-1">Camera Type</label>
                    <input
                      type="text"
                      bind:value={editForm.camera_type}
                      placeholder="e.g., FANCAM, VERTICAL FANCAM"
                      class="w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-2 focus:ring-pink-500 focus:border-pink-500"
                    />
                  </div>

                  {#if saveError}
                    <div class="bg-red-50 border border-red-200 text-red-700 px-4 py-2 rounded-md text-sm">
                      {saveError}
                    </div>
                  {/if}

                  <div class="flex gap-2 pt-2">
                    <button
                      on:click={handleSave}
                      disabled={saving}
                      class="px-4 py-2 bg-pink-600 text-white rounded-md hover:bg-pink-700 disabled:opacity-50"
                    >
                      {saving ? 'Saving...' : 'Save Changes'}
                    </button>
                    <button
                      on:click={handleCancel}
                      disabled={saving}
                      class="px-4 py-2 border border-gray-300 text-gray-700 rounded-md hover:bg-gray-50 disabled:opacity-50"
                    >
                      Cancel
                    </button>
                  </div>
                </div>
              {:else}
                <dl class="grid grid-cols-1 sm:grid-cols-2 gap-4">
                  <div>
                    <dt class="text-sm font-medium text-gray-500">Performance Date</dt>
                    <dd class="text-gray-900">{video.perf_date ? formatDateDisplay(video.perf_date) : '-'}</dd>
                  </div>
                  <div>
                    <dt class="text-sm font-medium text-gray-500">Group</dt>
                    <dd class="text-gray-900">{video.group_name || '-'}</dd>
                  </div>
                  <div>
                    <dt class="text-sm font-medium text-gray-500">Artist</dt>
                    <dd class="text-gray-900">{video.artist_name || '-'}</dd>
                  </div>
                  <div>
                    <dt class="text-sm font-medium text-gray-500">Song</dt>
                    <dd class="text-gray-900">{video.song_title || '-'}</dd>
                  </div>
                  <div>
                    <dt class="text-sm font-medium text-gray-500">Event</dt>
                    <dd class="text-gray-900">{video.event || '-'}</dd>
                  </div>
                  <div>
                    <dt class="text-sm font-medium text-gray-500">Camera Type</dt>
                    <dd class="text-gray-900">{video.camera_type || '-'}</dd>
                  </div>
                </dl>
              {/if}
            </div>

            <!-- Action Buttons (placeholders) -->
            <div class="border-t pt-4 mt-4">
              <h3 class="text-sm font-medium text-gray-500 mb-2">Actions</h3>
              <div class="flex flex-wrap gap-2">
                <button
                  disabled
                  class="px-4 py-2 bg-gray-100 text-gray-500 rounded-md cursor-not-allowed text-sm"
                  title="Coming soon"
                >
                  Confirm Download
                </button>
                <button
                  disabled
                  class="px-4 py-2 bg-gray-100 text-gray-500 rounded-md cursor-not-allowed text-sm"
                  title="Coming soon"
                >
                  Rename File
                </button>
                <button
                  disabled
                  class="px-4 py-2 bg-gray-100 text-gray-500 rounded-md cursor-not-allowed text-sm"
                  title="Coming soon"
                >
                  Mark Complete
                </button>
              </div>
            </div>

            <!-- Preview Images Section (placeholder) -->
            <div class="border-t pt-4 mt-4">
              <h3 class="text-sm font-medium text-gray-500 mb-2">Preview Images</h3>
              <div class="text-gray-400 text-sm italic">
                No preview images available yet.
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  {/if}
</div>

// apps/web/src/components/VideoCard.tsx
import {
  Alert,
  Button,
  Card,
  Col,
  Descriptions,
  Divider,
  Empty,
  Flex,
  Form,
  Input,
  Modal,
  Row,
  Select,
  Space,
  Spin,
  Tag,
  Tooltip,
  Typography,
  message,
} from 'antd';
import { CopyOutlined } from '@ant-design/icons';
import { useEffect, useState } from 'react';
import {
  addTagToVideo,
  buildFileCommand,
  getVideo,
  ignoreVideo,
  llmParseVideo,
  type ParserLog,
  reparseVideo,
  resyncVideo,
  removeTagFromVideo,
  updateMetadata,
  type Video,
} from '../api';
import AutocompleteField from './AutocompleteField';
import SongTitlesField from './SongTitlesField';
import AddToListModal from './AddToListModal';
import { getTagColor } from '../utils/tagColors';
import { formatDuration } from '../utils/formatDuration';
import OperationLogWidget from './OperationLogWidget';

const { Text, Title } = Typography;

interface EditForm {
  perf_date: string;
  group_name: string;
  artist_name: string;
  song_titles: string[];
  event: string;
  camera_type: string;
}

function songsToTitles(video: Video): string[] {
  if (video.songs?.length) return video.songs.map((song) => song.title);
  if (!video.song_title) return [];
  return video.song_title
    .split(/\s*\+\s*/)
    .map((song) => song.trim())
    .filter(Boolean);
}

function formatDateForEdit(dateString: string | null) {
  if (!dateString) return '';
  const date = new Date(dateString);
  const year = String(date.getFullYear()).slice(-2);
  const month = String(date.getMonth() + 1).padStart(2, '0');
  const day = String(date.getDate()).padStart(2, '0');
  return `${year}${month}${day}`;
}

function toForm(video: Video): EditForm {
  return {
    perf_date: formatDateForEdit(video.perf_date),
    group_name: video.group_name || '',
    artist_name: video.artist_name || '',
    song_titles: songsToTitles(video),
    event: video.event ? video.event.replace('@', '') : '',
    camera_type: video.camera_type || '',
  };
}

function formatDateDisplay(dateString: string | null | undefined): string {
  if (!dateString) return '-';
  return new Date(dateString).toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });
}

const SectionHeader = ({ title, extra }: { title: string; extra?: React.ReactNode }) => (
  <Flex align="center" gap={16} style={{ marginBottom: 16 }}>
    <Text strong style={{ fontSize: 14, whiteSpace: 'nowrap' }}>
      {title}
    </Text>
    <div style={{ flex: 1, height: 1, backgroundColor: '#f0f0f0' }} />
    {extra}
  </Flex>
);

interface VideoCardProps {
  videoId: number;
  onChanged?: () => void;
}

function VideoCard({ videoId, onChanged }: VideoCardProps) {
  const [video, setVideo] = useState<Video | null>(null);
  const [form, setForm] = useState<EditForm | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [editing, setEditing] = useState(false);
  const [saving, setSaving] = useState(false);
  const [newTagName, setNewTagName] = useState('');
  const [tagLoading, setTagLoading] = useState(false);
  const [presetTagLoading, setPresetTagLoading] = useState<'short' | 'private' | null>(null);
  const [llmParsing, setLlmParsing] = useState(false);
  const [reparsing, setReparsing] = useState(false);
  const [resyncing, setResyncing] = useState(false);
  const [fileCommandLoading, setFileCommandLoading] = useState(false);
  const [addToListOpen, setAddToListOpen] = useState(false);
  const [tagSuggestions, setTagSuggestions] = useState<string[]>([]);
  const [operationLog, setOperationLog] = useState<
    | { type: 'reparse'; log: ParserLog }
    | {
        type: 'resync';
        log: {
          youtubeResponse?: unknown;
          youtubeError?: string;
          parseLog: ParserLog;
        };
      }
    | null
  >(null);

  const requiresManualTagConfirmation = (tagName: string) =>
    ['short', 'private'].includes(tagName.trim().toLowerCase());

  const fetchVideo = async () => {
    if (!videoId) return;
    setLoading(true);
    setError(null);
    try {
      const data = await getVideo(String(videoId));
      setVideo(data);
      setForm(toForm(data));
      setTagSuggestions((data.tags ?? []).map((tag) => tag.name));
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to fetch video');
    } finally {
      setLoading(false);
    }
  };

  // Refetch the video AND notify the parent list so it can refresh too.
  const refresh = async () => {
    await fetchVideo();
    onChanged?.();
  };

  const handleAddTag = async () => {
    if (!video || !newTagName.trim()) return;
    const tagName = newTagName.trim();
    if (requiresManualTagConfirmation(tagName)) {
      Modal.confirm({
        title: `Add "${tagName}" tag?`,
        content: `This tag affects filtering and workflow. Do you want to continue?`,
        okText: 'Yes, add tag',
        cancelText: 'Cancel',
        onOk: () => handleAddTagConfirmed(tagName, true),
      });
      return;
    }
    await handleAddTagConfirmed(tagName, false);
  };

  const handleAddTagConfirmed = async (tagName: string, confirm: boolean) => {
    if (!video) return;
    setTagLoading(true);
    try {
      await addTagToVideo(video.id, tagName, confirm);
      message.success('Tag added');
      setNewTagName('');
      await refresh();
    } catch (err) {
      message.error(err instanceof Error ? err.message : 'Failed to add tag');
    } finally {
      setTagLoading(false);
    }
  };

  const handleAddPresetTag = async (tagName: 'short' | 'private') => {
    if (!video) return;
    Modal.confirm({
      title: `Add "${tagName}" tag?`,
      content: `This tag affects filtering and workflow. Do you want to continue?`,
      okText: 'Yes, add tag',
      cancelText: 'Cancel',
      onOk: async () => {
        setPresetTagLoading(tagName);
        try {
          await addTagToVideo(video.id, tagName, true);
          message.success(`Tag "${tagName}" added`);
          await refresh();
        } catch (err) {
          message.error(err instanceof Error ? err.message : `Failed to add ${tagName} tag`);
        } finally {
          setPresetTagLoading(null);
        }
      },
    });
  };

  const handleIgnore = async () => {
    if (!video || video.status === 'ignored') return;
    Modal.confirm({
      title: 'Ignore this video?',
      content: 'Are you sure you want to ignore this video? It will be hidden from views.',
      okText: 'Ignore',
      okButtonProps: { danger: true },
      cancelText: 'Cancel',
      onOk: async () => {
        try {
          await ignoreVideo(video.id);
          message.success('Video ignored');
          await refresh();
        } catch (err) {
          message.error(err instanceof Error ? err.message : 'Failed to ignore video');
        }
      },
    });
  };

  const handleLlmParse = async () => {
    if (!video) return;
    setLlmParsing(true);
    try {
      await llmParseVideo(video.id);
      message.success('LLM parse completed');
      await refresh();
    } catch (err) {
      message.error(err instanceof Error ? err.message : 'Failed LLM parse');
    } finally {
      setLlmParsing(false);
    }
  };

  const handleReparse = async () => {
    if (!video) return;
    setReparsing(true);
    try {
      const response = await reparseVideo(video.id);
      setOperationLog({ type: 'reparse', log: response.reparseLog });
      message.success('Reparse completed');
      await refresh();
    } catch (err) {
      message.error(err instanceof Error ? err.message : 'Failed to reparse video');
    } finally {
      setReparsing(false);
    }
  };

  const handleResync = async () => {
    if (!video) return;
    setResyncing(true);
    try {
      const response = await resyncVideo(video.id);
      setOperationLog({ type: 'resync', log: response.resyncLog });
      message.success('Resync completed');
      await refresh();
    } catch (err) {
      message.error(err instanceof Error ? err.message : 'Failed to resync video');
    } finally {
      setResyncing(false);
    }
  };

  const handleFileCommand = async () => {
    if (!video) return;
    setFileCommandLoading(true);
    try {
      const { command } = await buildFileCommand([video.id]);
      await navigator.clipboard.writeText(command);
      message.success('Команда скопирована в буфер');
    } catch (err) {
      message.error(err instanceof Error ? err.message : 'Не удалось сформировать команду');
    } finally {
      setFileCommandLoading(false);
    }
  };

  const handleRemoveTag = async (tagId: number) => {
    if (!video) return;
    setTagLoading(true);
    try {
      await removeTagFromVideo(video.id, tagId);
      message.success('Tag removed');
      await refresh();
    } catch (err) {
      message.error(err instanceof Error ? err.message : 'Failed to remove tag');
    } finally {
      setTagLoading(false);
    }
  };

  useEffect(() => {
    void fetchVideo();
  }, [videoId]);

  const handleSave = async () => {
    if (!video || !form) return;
    setSaving(true);
    try {
      await updateMetadata(video.id, {
        perf_date: form.perf_date || null,
        group_name: form.group_name || null,
        artist_name: form.artist_name || null,
        song_titles: form.song_titles,
        event: form.event ? '@' + form.event.toUpperCase() : null,
        camera_type: form.camera_type || null,
      });
      message.success('Metadata updated');
      setEditing(false);
      await refresh();
    } catch (err) {
      message.error(err instanceof Error ? err.message : 'Failed to save changes');
    } finally {
      setSaving(false);
    }
  };

  if (loading) return <Spin size="large" fullscreen />;
  if (error) return <Alert type="error" message={error} />;
  if (!video || !form) return <Alert type="warning" message="Video not found" />;

  return (
    <div>
      <Card
        bordered={false}
        style={{
          boxShadow: '0 6px 20px rgba(0,0,0,0.06)',
          borderRadius: 12,
          overflow: 'hidden',
        }}
      >
        {/* Header */}
        <Flex justify="space-between" align="flex-start" gap={12} wrap style={{ marginBottom: 24 }}>
          <Title level={3} style={{ margin: 0, fontWeight: 600 }}>
            {video.original_title}
          </Title>
          <Space>
            <Tag
              color={
                video.status === 'ignored'
                  ? 'default'
                  : video.status === 'processed'
                    ? 'success'
                    : 'magenta'
              }
              style={{ textTransform: 'capitalize', fontWeight: 500 }}
            >
              {video.status}
            </Tag>
            <Button onClick={() => void handleReparse()} loading={reparsing} size="small">
              Reparse
            </Button>
            <Button onClick={() => void handleResync()} loading={resyncing} size="small">
              Resync
            </Button>
            <Button
              danger
              variant="outlined"
              onClick={() => void handleIgnore()}
              disabled={video.status === 'ignored'}
              size="small"
            >
              Ignore
            </Button>
          </Space>
        </Flex>

        <Divider style={{ margin: '0 0 24px 0' }} />

        <Row gutter={[32, 32]}>
          {/* Left Column - Thumbnail */}
          <Col xs={24} md={9} lg={8}>
            <div
              style={{
                position: 'relative',
                borderRadius: 12,
                overflow: 'hidden',
                boxShadow: '0 8px 24px rgba(0,0,0,0.12)',
              }}
            >
              <img
                src={`https://img.youtube.com/vi/${video.youtube_id}/maxresdefault.jpg`}
                alt="Thumbnail"
                style={{ width: '100%', display: 'block', aspectRatio: '16/9', objectFit: 'cover' }}
              />
              <div
                style={{
                  position: 'absolute',
                  inset: 0,
                  background: 'linear-gradient(to bottom, rgba(0,0,0,0.1), rgba(0,0,0,0.4))',
                  opacity: 0,
                  transition: 'opacity 0.2s',
                  display: 'flex',
                  alignItems: 'center',
                  justifyContent: 'center',
                }}
                onMouseEnter={(e) => (e.currentTarget.style.opacity = '1')}
                onMouseLeave={(e) => (e.currentTarget.style.opacity = '0')}
              >
                <div
                  style={{
                    width: 56,
                    height: 56,
                    background: 'rgba(255, 0, 0, 0.9)',
                    borderRadius: '50%',
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'center',
                    marginLeft: 6,
                  }}
                >
                  <span style={{ color: 'white', fontSize: 24, lineHeight: 1 }}>▶</span>
                </div>
              </div>
            </div>
            <Button
              type="link"
              href={`https://www.youtube.com/watch?v=${video.youtube_id}`}
              target="_blank"
              style={{ marginTop: 12, padding: 0, fontWeight: 500 }}
            >
              Open in YouTube ↗
            </Button>
          </Col>

          {/* Right Column - Details */}
          <Col
            xs={24}
            md={15}
            lg={16}
            style={{ display: 'flex', flexDirection: 'column', gap: 24 }}
          >
            {/* Basic Info (Clean, no borders) */}
            <Descriptions column={{ xs: 1, sm: 2 }} size="small">
              <Descriptions.Item label="Published">
                {formatDateDisplay(video.published_at)}
              </Descriptions.Item>
              <Descriptions.Item label="Duration">
                {formatDuration(video.duration_seconds)}
              </Descriptions.Item>
              <Descriptions.Item label="Channel">{video.channel_title || '-'}</Descriptions.Item>
              <Descriptions.Item label="Playlist">{video.playlist_title || '-'}</Descriptions.Item>
            </Descriptions>

            <div>
              <SectionHeader title="Description" />
              <Typography.Paragraph
                style={{ marginBottom: 0, whiteSpace: 'pre-wrap' }}
                ellipsis={{ rows: 4, expandable: true, symbol: 'Show more' }}
              >
                {video.description?.trim() || 'No description'}
              </Typography.Paragraph>
            </div>

            {/* Metadata Block */}
            <div>
              <SectionHeader
                title="Metadata"
                extra={
                  !editing ? (
                    <Button type="primary" ghost size="small" onClick={() => setEditing(true)}>
                      Edit Metadata
                    </Button>
                  ) : null
                }
              />

              {editing ? (
                <div
                  style={{
                    background: '#fafafa',
                    padding: 24,
                    borderRadius: 12,
                    border: '1px solid #f0f0f0',
                    // Grid гарантирует, что вложенные Row/Col не будут схлопываться
                    display: 'grid',
                    gap: 16,
                  }}
                >
                  <Row gutter={16}>
                    <Col xs={24} sm={12}>
                      <AutocompleteField
                        label="Performance Date (YYMMDD)"
                        style={{ width: '100%' }}
                        type="group"
                        placeholder="e.g., 240315"
                        value={form.perf_date}
                        onChange={(value) =>
                          setForm((prev) => (prev ? { ...prev, perf_date: value } : prev))
                        }
                      />
                    </Col>
                    <Col xs={24} sm={12}>
                      <AutocompleteField
                        label="Group Name"
                        style={{ width: '100%' }}
                        type="group"
                        placeholder="Enter group name"
                        value={form.group_name}
                        onChange={(value) =>
                          setForm((prev) => (prev ? { ...prev, group_name: value } : prev))
                        }
                      />
                    </Col>
                  </Row>

                  <Row gutter={16}>
                    <Col xs={24} sm={12}>
                      <AutocompleteField
                        style={{ width: '100%' }}
                        type="artist"
                        placeholder="Enter artist name"
                        value={form.artist_name}
                        onChange={(value) =>
                          setForm((prev) => (prev ? { ...prev, artist_name: value } : prev))
                        }
                      />
                    </Col>
                    <Col xs={24} sm={12}>
                      <SongTitlesField
                        style={{ width: '100%' }}
                        placeholder="Enter song titles"
                        value={form.song_titles}
                        onChange={(value) =>
                          setForm((prev) => (prev ? { ...prev, song_titles: value } : prev))
                        }
                      />
                    </Col>
                  </Row>

                  <Row gutter={16}>
                    <Col xs={24} sm={12}>
                      <AutocompleteField
                        type="event"
                        placeholder="Enter event"
                        value={form.event}
                        style={{ width: '100%' }}
                        onChange={(value) =>
                          setForm((prev) => (prev ? { ...prev, event: value } : prev))
                        }
                      />
                    </Col>
                    <Col xs={24} sm={12}>
                      <Form.Item label="Camera Type" style={{ marginBottom: 0, width: '100%' }}>
                        <Input
                          style={{ width: '100%' }}
                          placeholder="Enter camera type"
                          value={form.camera_type}
                          onChange={(event) =>
                            setForm((prev) =>
                              prev ? { ...prev, camera_type: event.target.value } : prev,
                            )
                          }
                        />
                      </Form.Item>
                    </Col>
                  </Row>

                  <Flex gap={12} justify="flex-end" style={{ marginTop: 8 }}>
                    <Button
                      onClick={() => {
                        setForm(toForm(video));
                        setEditing(false);
                      }}
                      disabled={saving}
                    >
                      Cancel
                    </Button>
                    <Button type="primary" onClick={() => void handleSave()} loading={saving}>
                      Save Changes
                    </Button>
                  </Flex>
                </div>
              ) : (
                <Descriptions bordered column={2} size="small">
                  <Descriptions.Item label="Performance Date">
                    {formatDateDisplay(video.perf_date)}
                  </Descriptions.Item>
                  <Descriptions.Item label="Group">{video.group_name || '-'}</Descriptions.Item>
                  <Descriptions.Item label="Artist">{video.artist_name || '-'}</Descriptions.Item>
                  <Descriptions.Item label="Song">
                    {songsToTitles(video).join(' + ') || '-'}
                  </Descriptions.Item>
                  <Descriptions.Item label="Event">{video.event || '-'}</Descriptions.Item>
                  <Descriptions.Item label="Camera Type">
                    {video.camera_type || '-'}
                  </Descriptions.Item>
                  <Descriptions.Item label="Own group song">
                    {video.is_own_group_song === undefined || video.is_own_group_song === null
                      ? 'Unknown'
                      : video.is_own_group_song
                        ? 'Yes'
                        : 'No'}
                  </Descriptions.Item>
                  <Descriptions.Item label="Own artist song">
                    {video.is_own_artist_song === undefined || video.is_own_artist_song === null
                      ? 'Unknown'
                      : video.is_own_artist_song
                        ? 'Yes'
                        : 'No'}
                  </Descriptions.Item>
                </Descriptions>
              )}
            </div>

            {/* Tags Block */}
            <div>
              <SectionHeader title="Tags" />

              <div
                style={{
                  background: '#fafafa',
                  padding: 16,
                  borderRadius: 12,
                  border: '1px solid #f0f0f0',
                  display: 'grid',
                  gap: 16,
                }}
              >
                <Space wrap size={[8, 8]}>
                  {(video.tags ?? []).length > 0 ? (
                    video.tags?.map((tag) => (
                      <Tag
                        key={tag.id}
                        color={getTagColor(tag.name)}
                        closable
                        onClose={(event) => {
                          event.preventDefault();
                          void handleRemoveTag(tag.id);
                        }}
                        style={{ padding: '4px 12px', borderRadius: 4 }}
                      >
                        {tag.name}
                      </Tag>
                    ))
                  ) : (
                    <Text type="secondary" style={{ fontStyle: 'italic' }}>
                      No tags added yet
                    </Text>
                  )}
                </Space>

                <Space wrap size={8}>
                  <Tooltip title="Mark as a Shorts video">
                    <Button
                      size="small"
                      icon={<span style={{ color: '#52c41a' }}>●</span>}
                      style={{ borderColor: '#b7eb8f', color: '#389e0d', background: '#f6ffed' }}
                      onClick={() => void handleAddPresetTag('short')}
                      loading={presetTagLoading === 'short'}
                      disabled={presetTagLoading !== null}
                    >
                      Shorts
                    </Button>
                  </Tooltip>
                  <Tooltip title="Mark as a Private/Unlisted video">
                    <Button
                      size="small"
                      icon={<span style={{ color: '#fa8c16' }}>●</span>}
                      style={{ borderColor: '#ffd591', color: '#d46b08', background: '#fff7e6' }}
                      onClick={() => void handleAddPresetTag('private')}
                      loading={presetTagLoading === 'private'}
                      disabled={presetTagLoading !== null}
                    >
                      Private
                    </Button>
                  </Tooltip>
                </Space>

                <Space.Compact style={{ width: '100%', maxWidth: 400 }}>
                  <Select
                    showSearch
                    allowClear
                    style={{ width: '100%' }}
                    value={newTagName || undefined}
                    placeholder="Add custom tag..."
                    options={tagSuggestions.map((name) => ({ value: name, label: name }))}
                    onChange={(value) => setNewTagName(value || '')}
                    onSearch={(value) => setNewTagName(value)}
                  />
                  <Button type="primary" onClick={() => void handleAddTag()} loading={tagLoading}>
                    Add
                  </Button>
                </Space.Compact>
              </div>
            </div>

            {/* Actions Block */}
            <div>
              <SectionHeader title="Actions" />
              <Space wrap>
                <Button onClick={() => void handleLlmParse()} loading={llmParsing}>
                  ✨ LLM Parse Metadata
                </Button>
                <Button onClick={() => setAddToListOpen(true)}>Add to list</Button>
                <Tooltip title="Сформировать команду для файлов и скопировать в буфер">
                  <Button
                    icon={<CopyOutlined />}
                    onClick={() => void handleFileCommand()}
                    loading={fileCommandLoading}
                  >
                    Команда для файлов
                  </Button>
                </Tooltip>
              </Space>
            </div>

            {/* Previews Block */}
            <div>
              <SectionHeader title="Preview Images" />
              <Empty
                image={Empty.PRESENTED_IMAGE_SIMPLE}
                description={<Text type="secondary">No preview images generated yet</Text>}
              />
            </div>
          </Col>
        </Row>

        {operationLog ? (
          <OperationLogWidget
            type={operationLog.type}
            log={operationLog.log}
            onClear={() => setOperationLog(null)}
          />
        ) : null}
      </Card>

      <AddToListModal
        open={addToListOpen}
        onClose={() => setAddToListOpen(false)}
        videoIds={[video.id]}
        onSuccess={() => void refresh()}
      />
    </div>
  );
}

export default VideoCard;
