// client/src/components/VideoCard.tsx
import {
  Alert,
  Button,
  Card,
  Col,
  Descriptions,
  Divider,
  Flex,
  Form,
  Input,
  Modal,
  Row,
  Select,
  Space,
  Spin,
  Tag,
  Tooltip,
  Typography,
  message,
} from 'antd';
import { useEffect, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { addTagToVideo, getVideo, removeTagFromVideo, updateMetadata, type Video } from '../api';
import AutocompleteInput from './AutocompleteInput';
import { getTagColor } from '../utils/tagColors';

interface EditForm {
  perf_date: string;
  group_name: string;
  artist_name: string;
  song_title: string;
  event: string;
  camera_type: string;
}

function formatDateForEdit(dateString: string | null) {
  if (!dateString) return '';
  const date = new Date(dateString);
  const year = String(date.getFullYear()).slice(-2);
  const month = String(date.getMonth() + 1).padStart(2, '0');
  const day = String(date.getDate()).padStart(2, '0');
  return `${year}${month}${day}`;
}

function toForm(video: Video): EditForm {
  return {
    perf_date: formatDateForEdit(video.perf_date),
    group_name: video.group_name || '',
    artist_name: video.artist_name || '',
    song_title: video.song_title || '',
    event: video.event ? video.event.replace('@', '') : '',
    camera_type: video.camera_type || '',
  };
}

function formatDateDisplay(dateString: string | null | undefined): string {
  if (!dateString) return '-';
  return new Date(dateString).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
}

function VideoCard() {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();
  const [video, setVideo] = useState<Video | null>(null);
  const [form, setForm] = useState<EditForm | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [editing, setEditing] = useState(false);
  const [saving, setSaving] = useState(false);
  const [newTagName, setNewTagName] = useState('');
  const [tagLoading, setTagLoading] = useState(false);
  const [presetTagLoading, setPresetTagLoading] = useState<'short' | 'private' | null>(null);
  const [tagSuggestions, setTagSuggestions] = useState<string[]>([]);
  const requiresManualTagConfirmation = (tagName: string) =>
    ['short', 'private'].includes(tagName.trim().toLowerCase());

  const fetchVideo = async () => {
    if (!id) return;
    setLoading(true);
    setError(null);
    try {
      const data = await getVideo(id);
      setVideo(data);
      setForm(toForm(data));
      setTagSuggestions((data.tags ?? []).map((tag) => tag.name));
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to fetch video');
    } finally {
      setLoading(false);
    }
  };

  const handleAddTag = async () => {
    if (!video || !newTagName.trim()) return;
    const tagName = newTagName.trim();
    if (requiresManualTagConfirmation(tagName)) {
      Modal.confirm({
        title: `Add "${tagName}" tag?`,
        content: `This tag affects filtering and workflow. Do you want to continue?`,
        okText: 'Yes, add tag',
        cancelText: 'Cancel',
        onOk: () => handleAddTagConfirmed(tagName, true),
      });
      return;
    }
    await handleAddTagConfirmed(tagName, false);
  };

  const handleAddTagConfirmed = async (tagName: string, confirm: boolean) => {
    if (!video) return;
    setTagLoading(true);
    try {
      await addTagToVideo(video.id, tagName, confirm);
      message.success('Tag added');
      setNewTagName('');
      await fetchVideo();
    } catch (err) {
      message.error(err instanceof Error ? err.message : 'Failed to add tag');
    } finally {
      setTagLoading(false);
    }
  };


  const handleAddPresetTag = async (tagName: 'short' | 'private') => {
    if (!video) return;
    Modal.confirm({
      title: `Add "${tagName}" tag?`,
      content: `This tag affects filtering and workflow. Do you want to continue?`,
      okText: 'Yes, add tag',
      cancelText: 'Cancel',
      onOk: async () => {
        setPresetTagLoading(tagName);
        try {
          await addTagToVideo(video.id, tagName, true);
          message.success(`Tag "${tagName}" added`);
          await fetchVideo();
        } catch (err) {
          message.error(err instanceof Error ? err.message : `Failed to add ${tagName} tag`);
        } finally {
          setPresetTagLoading(null);
        }
      },
    });
  };

  const handleRemoveTag = async (tagId: number) => {
    if (!video) return;
    setTagLoading(true);
    try {
      await removeTagFromVideo(video.id, tagId);
      message.success('Tag removed');
      await fetchVideo();
    } catch (err) {
      message.error(err instanceof Error ? err.message : 'Failed to remove tag');
    } finally {
      setTagLoading(false);
    }
  };

  useEffect(() => {
    void fetchVideo();
  }, [id]);

  const handleSave = async () => {
    if (!video || !form) return;
    setSaving(true);
    try {
      await updateMetadata(video.id, {
        perf_date: form.perf_date || null,
        group_name: form.group_name || null,
        artist_name: form.artist_name || null,
        song_title: form.song_title || null,
        event: form.event ? '@' + form.event.toUpperCase() : null,
        camera_type: form.camera_type || null,
      });
      message.success('Metadata updated');
      setEditing(false);
      await fetchVideo();
    } catch (err) {
      message.error(err instanceof Error ? err.message : 'Failed to save changes');
    } finally {
      setSaving(false);
    }
  };

  if (loading) return <Spin size="large" fullscreen />;
  if (error) return <Alert type="error" message={error} />;
  if (!video || !form) return <Alert type="warning" message="Video not found" />;

  return (
    <Space direction="vertical" size="large" style={{ width: '100%', maxWidth: 1100, margin: '0 auto' }}>
      <Button type="link" onClick={() => navigate('/videos')} style={{ paddingLeft: 0 }}>
        ← Back to Videos
      </Button>

      <Card>
        <Flex justify="space-between" align="center" gap={12} wrap>
          <Typography.Title level={3} style={{ margin: 0 }}>
            {video.original_title}
          </Typography.Title>
          <Tag color="magenta">{video.status}</Tag>
        </Flex>
        <Divider />

        <Row gutter={[24, 24]}>
          <Col xs={24} md={8}>
            <img
              src={`https://img.youtube.com/vi/${video.youtube_id}/maxresdefault.jpg`}
              alt="Thumbnail"
              style={{ width: '100%', borderRadius: 8 }}
            />
            <Button type="link" href={`https://www.youtube.com/watch?v=${video.youtube_id}`} target="_blank">
              Watch on YouTube
            </Button>
          </Col>
          <Col xs={24} md={16}>
            <Descriptions bordered column={1} size="small">
              <Descriptions.Item label="Published Date">{formatDateDisplay(video.published_at)}</Descriptions.Item>
              <Descriptions.Item label="Channel">{video.channel_title || '-'}</Descriptions.Item>
              <Descriptions.Item label="Playlist">{video.playlist_title || '-'}</Descriptions.Item>
            </Descriptions>

            <Divider orientation="left">Metadata</Divider>

            <Divider orientation="left">Tags</Divider>
            <Space direction="vertical" style={{ width: '100%' }}>
              <Space wrap>
                {(video.tags ?? []).length > 0 ? (
                  video.tags?.map((tag) => (
                    <Tag
                      key={tag.id}
                      color={getTagColor(tag.name)}
                      closable
                      onClose={(event) => {
                        event.preventDefault();
                        void handleRemoveTag(tag.id);
                      }}
                    >
                      {tag.name}
                    </Tag>
                  ))
                ) : (
                  <Typography.Text type="secondary">No tags yet</Typography.Text>
                )}
              </Space>

              <Space wrap>
                <Tooltip title="Add the 'short' tag to this video">
                  <Button
                    size="small"
                    style={{ borderColor: '#52c41a', color: '#389e0d' }}
                    onClick={() => void handleAddPresetTag('short')}
                    loading={presetTagLoading === 'short'}
                    disabled={presetTagLoading !== null}
                  >
                    Shorts
                  </Button>
                </Tooltip>
                <Tooltip title="Add the 'private' tag to this video">
                  <Button
                    size="small"
                    style={{ borderColor: '#fa8c16', color: '#d46b08' }}
                    onClick={() => void handleAddPresetTag('private')}
                    loading={presetTagLoading === 'private'}
                    disabled={presetTagLoading !== null}
                  >
                    Private
                  </Button>
                </Tooltip>
              </Space>

              <Space.Compact style={{ width: '100%' }}>
                <Select
                  showSearch
                  style={{ width: '100%' }}
                  value={newTagName || undefined}
                  placeholder="Type a tag name or choose an existing one"
                  options={tagSuggestions.map((name) => ({ value: name, label: name }))}
                  onChange={(value) => setNewTagName(value || '')}
                  onSearch={(value) => setNewTagName(value)}
                />
                <Button type="primary" onClick={() => void handleAddTag()} loading={tagLoading}>
                  Add Tag
                </Button>
              </Space.Compact>
            </Space>

            {editing ? (
              <Space direction="vertical" style={{ width: '100%' }}>
                <AutocompleteInput
                  label="Performance Date (YYMMDD)"
                  type="groups"
                  placeholder="e.g., 240315"
                  value={form.perf_date}
                  onChange={(value) => setForm((prev) => (prev ? { ...prev, perf_date: value } : prev))}
                />
                <AutocompleteInput
                  label="Group Name"
                  type="groups"
                  placeholder="Enter group name"
                  value={form.group_name}
                  onChange={(value) => setForm((prev) => (prev ? { ...prev, group_name: value } : prev))}
                />
                <AutocompleteInput
                  label="Artist Name"
                  type="artists"
                  placeholder="Enter artist name"
                  value={form.artist_name}
                  onChange={(value) => setForm((prev) => (prev ? { ...prev, artist_name: value } : prev))}
                />
                <AutocompleteInput
                  label="Song Title"
                  type="songs"
                  placeholder="Enter song title"
                  value={form.song_title}
                  onChange={(value) => setForm((prev) => (prev ? { ...prev, song_title: value } : prev))}
                />
                <AutocompleteInput
                  label="Event"
                  type="events"
                  placeholder="Enter event"
                  value={form.event}
                  onChange={(value) => setForm((prev) => (prev ? { ...prev, event: value } : prev))}
                />
                <Form.Item label="Camera Type" style={{ marginBottom: 0 }}>
                  <Input
                    value={form.camera_type}
                    onChange={(event) => setForm((prev) => (prev ? { ...prev, camera_type: event.target.value } : prev))}
                  />
                </Form.Item>
                <Space>
                  <Button type="primary" onClick={() => void handleSave()} loading={saving}>
                    Save Changes
                  </Button>
                  <Button
                    onClick={() => {
                      setForm(toForm(video));
                      setEditing(false);
                    }}
                    disabled={saving}
                  >
                    Cancel
                  </Button>
                </Space>
              </Space>
            ) : (
              <>
                <Descriptions bordered column={2} size="small">
                  <Descriptions.Item label="Performance Date">{formatDateDisplay(video.perf_date)}</Descriptions.Item>
                  <Descriptions.Item label="Group">{video.group_name || '-'}</Descriptions.Item>
                  <Descriptions.Item label="Artist">{video.artist_name || '-'}</Descriptions.Item>
                  <Descriptions.Item label="Song">{video.song_title || '-'}</Descriptions.Item>
                  <Descriptions.Item label="Event">{video.event || '-'}</Descriptions.Item>
                  <Descriptions.Item label="Camera Type">{video.camera_type || '-'}</Descriptions.Item>
                </Descriptions>
                <Button type="primary" ghost style={{ marginTop: 16 }} onClick={() => setEditing(true)}>
                  Edit
                </Button>
              </>
            )}

            <Divider orientation="left">Actions</Divider>
            <Space wrap>
              <Button disabled>Confirm Download</Button>
              <Button disabled>Rename File</Button>
              <Button disabled>Mark Complete</Button>
            </Space>
            <Divider orientation="left">Preview Images</Divider>
            <Typography.Text type="secondary">No preview images available yet.</Typography.Text>
          </Col>
        </Row>
      </Card>
    </Space>
  );
}

export default VideoCard;

// client/src/components/VideoCard.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { getVideo, updateMetadata, type Video } from '../api';
  import { goto } from 'svelte-spa-router';
  import AutocompleteInput from './AutocompleteInput.svelte';

  export let id: string;

  let video: Video | null = null;
  let loading: boolean = true;
  let error: string | null = null;
  
  // Edit mode state
  let isEditing: boolean = false;
  let editForm: {
    perf_date: string;
    group_name: string;
    artist_name: string;
    song_title: string;
    event: string;
    camera_type: string;
  } = {
    perf_date: '',
    group_name: '',
    artist_name: '',
    song_title: '',
    event: '',
    camera_type: '',
  };
  let saving: boolean = false;
  let saveError: string | null = null;

  async function fetchVideo() {
    loading = true;
    error = null;
    try {
      video = await getVideo(id);
      
      // Initialize edit form with current values
      editForm = {
        perf_date: formatDateForEdit(video.perf_date),
        group_name: video.group_name || '',
        artist_name: video.artist_name || '',
        song_title: video.song_title || '',
        event: video.event ? video.event.replace('@', '') : '',
        camera_type: video.camera_type || '',
      };
    } catch (err) {
      error = err instanceof Error ? err.message : 'Failed to fetch video';
    } finally {
      loading = false;
    }
  }

  function formatDateForEdit(dateString: string | null): string {
    if (!dateString) return '';
    const date = new Date(dateString);
    const year = String(date.getFullYear()).slice(-2);
    const month = String(date.getMonth() + 1).padStart(2, '0');
    const day = String(date.getDate()).padStart(2, '0');
    return `${year}${month}${day}`;
  }

  function toggleEditMode() {
    isEditing = !isEditing;
    saveError = null;
  }

  async function handleSave() {
    saving = true;
    saveError = null;
    try {
      const updateData = {
        perf_date: editForm.perf_date || null,
        group_name: editForm.group_name || null,
        artist_name: editForm.artist_name || null,
        song_title: editForm.song_title || null,
        event: editForm.event ? '@' + editForm.event.toUpperCase() : null,
        camera_type: editForm.camera_type || null,
      };
      
      video = await updateMetadata(id, updateData);
      isEditing = false;
      
      // Refresh the video data
      await fetchVideo();
    } catch (err) {
      saveError = err instanceof Error ? err.message : 'Failed to save changes';
    } finally {
      saving = false;
    }
  }

  function handleCancel() {
    if (video) {
      editForm = {
        perf_date: formatDateForEdit(video.perf_date),
        group_name: video.group_name || '',
        artist_name: video.artist_name || '',
        song_title: video.song_title || '',
        event: video.event ? video.event.replace('@', '') : '',
        camera_type: video.camera_type || '',
      };
    }
    isEditing = false;
    saveError = null;
  }

  function getStatusColor(status: string): string {
    switch (status) {
      case 'new': return 'bg-green-100 text-green-800';
      case 'needs_review': return 'bg-red-100 text-red-800';
      case 'pending': return 'bg-yellow-100 text-yellow-800';
      case 'processing': return 'bg-blue-100 text-blue-800';
      case 'ready': return 'bg-purple-100 text-purple-800';
      case 'completed': return 'bg-gray-100 text-gray-800';
      case 'error': return 'bg-red-200 text-red-900';
      default: return 'bg-gray-100 text-gray-800';
    }
  }

  function formatDateDisplay(dateString: string | null): string {
    if (!dateString) return '-';
    return new Date(dateString).toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
    });
  }

  function goBack() {
    goto('/videos');
  }

  onMount(() => {
    fetchVideo();
  });
</script>

<div class="p-6 max-w-5xl mx-auto">
  <button 
    on:click={goBack}
    class="mb-4 text-pink-600 hover:text-pink-800 font-medium"
  >
    ← Back to Videos
  </button>

  {#if loading}
    <div class="flex justify-center items-center py-12">
      <div class="animate-spin rounded-full h-12 w-12 border-b-2 border-pink-500"></div>
    </div>
  {:else if error}
    <div class="bg-red-50 border border-red-200 text-red-700 px-4 py-3 rounded-md">
      {error}
    </div>
  {:else if video}
    <div class="bg-white rounded-lg shadow-lg overflow-hidden">
      <!-- Header -->
      <div class="bg-gradient-to-r from-pink-500 to-purple-600 px-6 py-4">
        <div class="flex items-center justify-between">
          <h1 class="text-2xl font-bold text-white truncate">{video.original_title}</h1>
          <span class="inline-flex px-3 py-1 text-sm font-semibold rounded-full bg-white/20 text-white">
            {video.status}
          </span>
        </div>
      </div>

      <div class="p-6">
        <div class="grid grid-cols-1 md:grid-cols-3 gap-6">
          <!-- Thumbnail -->
          <div class="md:col-span-1">
            <img 
              src="https://img.youtube.com/vi/{video.youtube_id}/maxresdefault.jpg" 
              alt="Thumbnail"
              class="w-full rounded-lg shadow-md"
              on:error={(e) => {
                const target = e.target as HTMLImageElement;
                target.src = `https://img.youtube.com/vi/${video.youtube_id}/mqdefault.jpg`;
              }}
            />
            <a 
              href="https://www.youtube.com/watch?v={video.youtube_id}" 
              target="_blank" 
              rel="noopener noreferrer"
              class="mt-2 block text-center text-sm text-pink-600 hover:text-pink-800"
            >
              Watch on YouTube
            </a>
          </div>

          <!-- Details -->
          <div class="md:col-span-2 space-y-4">
            <div>
              <h3 class="text-sm font-medium text-gray-500">Published Date</h3>
              <p class="text-gray-900">{formatDateDisplay(video.published_at)}</p>
            </div>

            {#if video.channel_title}
              <div>
                <h3 class="text-sm font-medium text-gray-500">Channel</h3>
                <p class="text-gray-900">{video.channel_title}</p>
              </div>
            {/if}

            {#if video.playlist_title}
              <div>
                <h3 class="text-sm font-medium text-gray-500">Playlist</h3>
                <p class="text-gray-900">{video.playlist_title}</p>
              </div>
            {/if}

            <!-- Metadata Section -->
            <div class="border-t pt-4 mt-4">
              <div class="flex items-center justify-between mb-4">
                <h2 class="text-lg font-semibold text-gray-900">Metadata</h2>
                {#if !isEditing}
                  <button
                    on:click={toggleEditMode}
                    class="px-4 py-2 text-sm font-medium text-pink-600 border border-pink-600 rounded-md hover:bg-pink-50"
                  >
                    Edit
                  </button>
                {/if}
              </div>

              {#if isEditing}
                <div class="space-y-4">
                  <AutocompleteInput
                    label="Performance Date (YYMMDD)"
                    type="groups"
                    placeholder="e.g., 240315"
                    bind:value={editForm.perf_date}
                  />
                  <AutocompleteInput
                    label="Group Name"
                    type="groups"
                    placeholder="Enter group name"
                    bind:value={editForm.group_name}
                  />
                  <AutocompleteInput
                    label="Artist Name"
                    type="artists"
                    placeholder="Enter artist name"
                    bind:value={editForm.artist_name}
                  />
                  <AutocompleteInput
                    label="Song Title"
                    type="songs"
                    placeholder="Enter song title"
                    bind:value={editForm.song_title}
                  />
                  <AutocompleteInput
                    label="Event"
                    type="events"
                    placeholder="Enter event name"
                    bind:value={editForm.event}
                  />
                  <div>
                    <label class="block text-sm font-medium text-gray-700 mb-1">Camera Type</label>
                    <input
                      type="text"
                      bind:value={editForm.camera_type}
                      placeholder="e.g., FANCAM, VERTICAL FANCAM"
                      class="w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-2 focus:ring-pink-500 focus:border-pink-500"
                    />
                  </div>

                  {#if saveError}
                    <div class="bg-red-50 border border-red-200 text-red-700 px-4 py-2 rounded-md text-sm">
                      {saveError}
                    </div>
                  {/if}

                  <div class="flex gap-2 pt-2">
                    <button
                      on:click={handleSave}
                      disabled={saving}
                      class="px-4 py-2 bg-pink-600 text-white rounded-md hover:bg-pink-700 disabled:opacity-50"
                    >
                      {saving ? 'Saving...' : 'Save Changes'}
                    </button>
                    <button
                      on:click={handleCancel}
                      disabled={saving}
                      class="px-4 py-2 border border-gray-300 text-gray-700 rounded-md hover:bg-gray-50 disabled:opacity-50"
                    >
                      Cancel
                    </button>
                  </div>
                </div>
              {:else}
                <dl class="grid grid-cols-1 sm:grid-cols-2 gap-4">
                  <div>
                    <dt class="text-sm font-medium text-gray-500">Performance Date</dt>
                    <dd class="text-gray-900">{video.perf_date ? formatDateDisplay(video.perf_date) : '-'}</dd>
                  </div>
                  <div>
                    <dt class="text-sm font-medium text-gray-500">Group</dt>
                    <dd class="text-gray-900">{video.group_name || '-'}</dd>
                  </div>
                  <div>
                    <dt class="text-sm font-medium text-gray-500">Artist</dt>
                    <dd class="text-gray-900">{video.artist_name || '-'}</dd>
                  </div>
                  <div>
                    <dt class="text-sm font-medium text-gray-500">Song</dt>
                    <dd class="text-gray-900">{video.song_title || '-'}</dd>
                  </div>
                  <div>
                    <dt class="text-sm font-medium text-gray-500">Event</dt>
                    <dd class="text-gray-900">{video.event || '-'}</dd>
                  </div>
                  <div>
                    <dt class="text-sm font-medium text-gray-500">Camera Type</dt>
                    <dd class="text-gray-900">{video.camera_type || '-'}</dd>
                  </div>
                </dl>
              {/if}
            </div>

            <!-- Action Buttons (placeholders) -->
            <div class="border-t pt-4 mt-4">
              <h3 class="text-sm font-medium text-gray-500 mb-2">Actions</h3>
              <div class="flex flex-wrap gap-2">
                <button
                  disabled
                  class="px-4 py-2 bg-gray-100 text-gray-500 rounded-md cursor-not-allowed text-sm"
                  title="Coming soon"
                >
                  Confirm Download
                </button>
                <button
                  disabled
                  class="px-4 py-2 bg-gray-100 text-gray-500 rounded-md cursor-not-allowed text-sm"
                  title="Coming soon"
                >
                  Rename File
                </button>
                <button
                  disabled
                  class="px-4 py-2 bg-gray-100 text-gray-500 rounded-md cursor-not-allowed text-sm"
                  title="Coming soon"
                >
                  Mark Complete
                </button>
              </div>
            </div>

            <!-- Preview Images Section (placeholder) -->
            <div class="border-t pt-4 mt-4">
              <h3 class="text-sm font-medium text-gray-500 mb-2">Preview Images</h3>
              <div class="text-gray-400 text-sm italic">
                No preview images available yet.
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  {/if}
</div>
